server:
  port: 8081
  servlet:
    context-path: /spring-boot
spring:
  application:
    name: msl-admin-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #测试环境
    url: jdbc:mysql://localhost:3306/yunpay?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
  http:
    converters:
      preferred-json-mapper: fastjson
  messages:
    basename: in18/messages
  redis:
    #测试环境
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 500
        max-active: 2000
        min-idle: 50
        max-wait: 2000
    port: 6379
    timeout: 3000
    database: 8
mybatis:
  mapper-locations: classpath*:mybatisxml/*Mapper.xml
  type-aliases-package: com.msl.mybatis.entity
