package com.msl.mybatis.entity;

import java.io.Serializable;

public class YpAppSwitch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_app_switch.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_app_switch.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_app_switch.app_value
     *
     * @mbggenerated
     */
    private Integer appValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_app_switch.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_app_switch.isshow
     *
     * @mbggenerated
     */
    private Short isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_app_switch
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_app_switch.sid
     *
     * @return the value of yp_app_switch.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_app_switch.sid
     *
     * @param sid the value for yp_app_switch.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_app_switch.app_key
     *
     * @return the value of yp_app_switch.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_app_switch.app_key
     *
     * @param appKey the value for yp_app_switch.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_app_switch.app_value
     *
     * @return the value of yp_app_switch.app_value
     *
     * @mbggenerated
     */
    public Integer getAppValue() {
        return appValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_app_switch.app_value
     *
     * @param appValue the value for yp_app_switch.app_value
     *
     * @mbggenerated
     */
    public void setAppValue(Integer appValue) {
        this.appValue = appValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_app_switch.mark
     *
     * @return the value of yp_app_switch.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_app_switch.mark
     *
     * @param mark the value for yp_app_switch.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_app_switch.isshow
     *
     * @return the value of yp_app_switch.isshow
     *
     * @mbggenerated
     */
    public Short getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_app_switch.isshow
     *
     * @param isshow the value for yp_app_switch.isshow
     *
     * @mbggenerated
     */
    public void setIsshow(Short isshow) {
        this.isshow = isshow;
    }
}