package com.msl.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class YpBankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public YpBankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankIdIsNull() {
            addCriterion("bank_id is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("bank_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(Integer value) {
            addCriterion("bank_id =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(Integer value) {
            addCriterion("bank_id <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(Integer value) {
            addCriterion("bank_id >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bank_id >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(Integer value) {
            addCriterion("bank_id <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(Integer value) {
            addCriterion("bank_id <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<Integer> values) {
            addCriterion("bank_id in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<Integer> values) {
            addCriterion("bank_id not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(Integer value1, Integer value2) {
            addCriterion("bank_id between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bank_id not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankPicIsNull() {
            addCriterion("bank_pic is null");
            return (Criteria) this;
        }

        public Criteria andBankPicIsNotNull() {
            addCriterion("bank_pic is not null");
            return (Criteria) this;
        }

        public Criteria andBankPicEqualTo(String value) {
            addCriterion("bank_pic =", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicNotEqualTo(String value) {
            addCriterion("bank_pic <>", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicGreaterThan(String value) {
            addCriterion("bank_pic >", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicGreaterThanOrEqualTo(String value) {
            addCriterion("bank_pic >=", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicLessThan(String value) {
            addCriterion("bank_pic <", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicLessThanOrEqualTo(String value) {
            addCriterion("bank_pic <=", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicLike(String value) {
            addCriterion("bank_pic like", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicNotLike(String value) {
            addCriterion("bank_pic not like", value, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicIn(List<String> values) {
            addCriterion("bank_pic in", values, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicNotIn(List<String> values) {
            addCriterion("bank_pic not in", values, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicBetween(String value1, String value2) {
            addCriterion("bank_pic between", value1, value2, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankPicNotBetween(String value1, String value2) {
            addCriterion("bank_pic not between", value1, value2, "bankPic");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNull() {
            addCriterion("bank_code is null");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNotNull() {
            addCriterion("bank_code is not null");
            return (Criteria) this;
        }

        public Criteria andBankCodeEqualTo(String value) {
            addCriterion("bank_code =", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotEqualTo(String value) {
            addCriterion("bank_code <>", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThan(String value) {
            addCriterion("bank_code >", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_code >=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThan(String value) {
            addCriterion("bank_code <", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThanOrEqualTo(String value) {
            addCriterion("bank_code <=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLike(String value) {
            addCriterion("bank_code like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotLike(String value) {
            addCriterion("bank_code not like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeIn(List<String> values) {
            addCriterion("bank_code in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotIn(List<String> values) {
            addCriterion("bank_code not in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeBetween(String value1, String value2) {
            addCriterion("bank_code between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotBetween(String value1, String value2) {
            addCriterion("bank_code not between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundIsNull() {
            addCriterion("bank_background is null");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundIsNotNull() {
            addCriterion("bank_background is not null");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundEqualTo(String value) {
            addCriterion("bank_background =", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundNotEqualTo(String value) {
            addCriterion("bank_background <>", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundGreaterThan(String value) {
            addCriterion("bank_background >", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("bank_background >=", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundLessThan(String value) {
            addCriterion("bank_background <", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundLessThanOrEqualTo(String value) {
            addCriterion("bank_background <=", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundLike(String value) {
            addCriterion("bank_background like", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundNotLike(String value) {
            addCriterion("bank_background not like", value, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundIn(List<String> values) {
            addCriterion("bank_background in", values, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundNotIn(List<String> values) {
            addCriterion("bank_background not in", values, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundBetween(String value1, String value2) {
            addCriterion("bank_background between", value1, value2, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBankBackgroundNotBetween(String value1, String value2) {
            addCriterion("bank_background not between", value1, value2, "bankBackground");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueIsNull() {
            addCriterion("background_pictrue is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueIsNotNull() {
            addCriterion("background_pictrue is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueEqualTo(String value) {
            addCriterion("background_pictrue =", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueNotEqualTo(String value) {
            addCriterion("background_pictrue <>", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueGreaterThan(String value) {
            addCriterion("background_pictrue >", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueGreaterThanOrEqualTo(String value) {
            addCriterion("background_pictrue >=", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueLessThan(String value) {
            addCriterion("background_pictrue <", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueLessThanOrEqualTo(String value) {
            addCriterion("background_pictrue <=", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueLike(String value) {
            addCriterion("background_pictrue like", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueNotLike(String value) {
            addCriterion("background_pictrue not like", value, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueIn(List<String> values) {
            addCriterion("background_pictrue in", values, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueNotIn(List<String> values) {
            addCriterion("background_pictrue not in", values, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueBetween(String value1, String value2) {
            addCriterion("background_pictrue between", value1, value2, "backgroundPictrue");
            return (Criteria) this;
        }

        public Criteria andBackgroundPictrueNotBetween(String value1, String value2) {
            addCriterion("background_pictrue not between", value1, value2, "backgroundPictrue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_bank
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_bank
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}