package com.msl.mybatis.entity;

import java.io.Serializable;

public class YpConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.config_id
     *
     * @mbggenerated
     */
    private Integer configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.config_group
     *
     * @mbggenerated
     */
    private String configGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.config_key
     *
     * @mbggenerated
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.config_value
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.config_mark
     *
     * @mbggenerated
     */
    private String configMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.isshow
     *
     * @mbggenerated
     */
    private Byte isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_config.lang
     *
     * @mbggenerated
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.config_id
     *
     * @return the value of yp_config.config_id
     *
     * @mbggenerated
     */
    public Integer getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.config_id
     *
     * @param configId the value for yp_config.config_id
     *
     * @mbggenerated
     */
    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.config_group
     *
     * @return the value of yp_config.config_group
     *
     * @mbggenerated
     */
    public String getConfigGroup() {
        return configGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.config_group
     *
     * @param configGroup the value for yp_config.config_group
     *
     * @mbggenerated
     */
    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.config_key
     *
     * @return the value of yp_config.config_key
     *
     * @mbggenerated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.config_key
     *
     * @param configKey the value for yp_config.config_key
     *
     * @mbggenerated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.config_value
     *
     * @return the value of yp_config.config_value
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.config_value
     *
     * @param configValue the value for yp_config.config_value
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.config_mark
     *
     * @return the value of yp_config.config_mark
     *
     * @mbggenerated
     */
    public String getConfigMark() {
        return configMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.config_mark
     *
     * @param configMark the value for yp_config.config_mark
     *
     * @mbggenerated
     */
    public void setConfigMark(String configMark) {
        this.configMark = configMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.isshow
     *
     * @return the value of yp_config.isshow
     *
     * @mbggenerated
     */
    public Byte getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.isshow
     *
     * @param isshow the value for yp_config.isshow
     *
     * @mbggenerated
     */
    public void setIsshow(Byte isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.sort
     *
     * @return the value of yp_config.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.sort
     *
     * @param sort the value for yp_config.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_config.lang
     *
     * @return the value of yp_config.lang
     *
     * @mbggenerated
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_config.lang
     *
     * @param lang the value for yp_config.lang
     *
     * @mbggenerated
     */
    public void setLang(String lang) {
        this.lang = lang;
    }
}