package com.msl.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class YpInterfaceStatistics implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.interface_desc
     *
     * @mbggenerated
     */
    private String interfaceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.interface_val
     *
     * @mbggenerated
     */
    private String interfaceVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.num
     *
     * @mbggenerated
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.statis_year
     *
     * @mbggenerated
     */
    private Integer statisYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.statis_month
     *
     * @mbggenerated
     */
    private Integer statisMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.statis_day
     *
     * @mbggenerated
     */
    private Integer statisDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.statis_hour
     *
     * @mbggenerated
     */
    private Integer statisHour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_interface_statistics.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_interface_statistics
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.id
     *
     * @return the value of yp_interface_statistics.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.id
     *
     * @param id the value for yp_interface_statistics.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.interface_desc
     *
     * @return the value of yp_interface_statistics.interface_desc
     *
     * @mbggenerated
     */
    public String getInterfaceDesc() {
        return interfaceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.interface_desc
     *
     * @param interfaceDesc the value for yp_interface_statistics.interface_desc
     *
     * @mbggenerated
     */
    public void setInterfaceDesc(String interfaceDesc) {
        this.interfaceDesc = interfaceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.interface_val
     *
     * @return the value of yp_interface_statistics.interface_val
     *
     * @mbggenerated
     */
    public String getInterfaceVal() {
        return interfaceVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.interface_val
     *
     * @param interfaceVal the value for yp_interface_statistics.interface_val
     *
     * @mbggenerated
     */
    public void setInterfaceVal(String interfaceVal) {
        this.interfaceVal = interfaceVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.num
     *
     * @return the value of yp_interface_statistics.num
     *
     * @mbggenerated
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.num
     *
     * @param num the value for yp_interface_statistics.num
     *
     * @mbggenerated
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.statis_year
     *
     * @return the value of yp_interface_statistics.statis_year
     *
     * @mbggenerated
     */
    public Integer getStatisYear() {
        return statisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.statis_year
     *
     * @param statisYear the value for yp_interface_statistics.statis_year
     *
     * @mbggenerated
     */
    public void setStatisYear(Integer statisYear) {
        this.statisYear = statisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.statis_month
     *
     * @return the value of yp_interface_statistics.statis_month
     *
     * @mbggenerated
     */
    public Integer getStatisMonth() {
        return statisMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.statis_month
     *
     * @param statisMonth the value for yp_interface_statistics.statis_month
     *
     * @mbggenerated
     */
    public void setStatisMonth(Integer statisMonth) {
        this.statisMonth = statisMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.statis_day
     *
     * @return the value of yp_interface_statistics.statis_day
     *
     * @mbggenerated
     */
    public Integer getStatisDay() {
        return statisDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.statis_day
     *
     * @param statisDay the value for yp_interface_statistics.statis_day
     *
     * @mbggenerated
     */
    public void setStatisDay(Integer statisDay) {
        this.statisDay = statisDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.statis_hour
     *
     * @return the value of yp_interface_statistics.statis_hour
     *
     * @mbggenerated
     */
    public Integer getStatisHour() {
        return statisHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.statis_hour
     *
     * @param statisHour the value for yp_interface_statistics.statis_hour
     *
     * @mbggenerated
     */
    public void setStatisHour(Integer statisHour) {
        this.statisHour = statisHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_interface_statistics.create_time
     *
     * @return the value of yp_interface_statistics.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_interface_statistics.create_time
     *
     * @param createTime the value for yp_interface_statistics.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}