package com.msl.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YpMerchantStatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public YpMerchantStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatisIdIsNull() {
            addCriterion("statis_id is null");
            return (Criteria) this;
        }

        public Criteria andStatisIdIsNotNull() {
            addCriterion("statis_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatisIdEqualTo(Integer value) {
            addCriterion("statis_id =", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdNotEqualTo(Integer value) {
            addCriterion("statis_id <>", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdGreaterThan(Integer value) {
            addCriterion("statis_id >", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("statis_id >=", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdLessThan(Integer value) {
            addCriterion("statis_id <", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdLessThanOrEqualTo(Integer value) {
            addCriterion("statis_id <=", value, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdIn(List<Integer> values) {
            addCriterion("statis_id in", values, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdNotIn(List<Integer> values) {
            addCriterion("statis_id not in", values, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdBetween(Integer value1, Integer value2) {
            addCriterion("statis_id between", value1, value2, "statisId");
            return (Criteria) this;
        }

        public Criteria andStatisIdNotBetween(Integer value1, Integer value2) {
            addCriterion("statis_id not between", value1, value2, "statisId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Long value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Long value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Long value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Long value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Long value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Long> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Long> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Long value1, Long value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Long value1, Long value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Long value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Long value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Long value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Long value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Long value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Long> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Long> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Long value1, Long value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Long value1, Long value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Long value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Long value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Long value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Long value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Long value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Long value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Long> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Long> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Long value1, Long value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Long value1, Long value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andStatisDateIsNull() {
            addCriterion("statis_date is null");
            return (Criteria) this;
        }

        public Criteria andStatisDateIsNotNull() {
            addCriterion("statis_date is not null");
            return (Criteria) this;
        }

        public Criteria andStatisDateEqualTo(Date value) {
            addCriterion("statis_date =", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateNotEqualTo(Date value) {
            addCriterion("statis_date <>", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateGreaterThan(Date value) {
            addCriterion("statis_date >", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateGreaterThanOrEqualTo(Date value) {
            addCriterion("statis_date >=", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateLessThan(Date value) {
            addCriterion("statis_date <", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateLessThanOrEqualTo(Date value) {
            addCriterion("statis_date <=", value, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateIn(List<Date> values) {
            addCriterion("statis_date in", values, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateNotIn(List<Date> values) {
            addCriterion("statis_date not in", values, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateBetween(Date value1, Date value2) {
            addCriterion("statis_date between", value1, value2, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisDateNotBetween(Date value1, Date value2) {
            addCriterion("statis_date not between", value1, value2, "statisDate");
            return (Criteria) this;
        }

        public Criteria andStatisMonthIsNull() {
            addCriterion("statis_month is null");
            return (Criteria) this;
        }

        public Criteria andStatisMonthIsNotNull() {
            addCriterion("statis_month is not null");
            return (Criteria) this;
        }

        public Criteria andStatisMonthEqualTo(Integer value) {
            addCriterion("statis_month =", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthNotEqualTo(Integer value) {
            addCriterion("statis_month <>", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthGreaterThan(Integer value) {
            addCriterion("statis_month >", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("statis_month >=", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthLessThan(Integer value) {
            addCriterion("statis_month <", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthLessThanOrEqualTo(Integer value) {
            addCriterion("statis_month <=", value, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthIn(List<Integer> values) {
            addCriterion("statis_month in", values, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthNotIn(List<Integer> values) {
            addCriterion("statis_month not in", values, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthBetween(Integer value1, Integer value2) {
            addCriterion("statis_month between", value1, value2, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStatisMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("statis_month not between", value1, value2, "statisMonth");
            return (Criteria) this;
        }

        public Criteria andStaticHourIsNull() {
            addCriterion("static_hour is null");
            return (Criteria) this;
        }

        public Criteria andStaticHourIsNotNull() {
            addCriterion("static_hour is not null");
            return (Criteria) this;
        }

        public Criteria andStaticHourEqualTo(Integer value) {
            addCriterion("static_hour =", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourNotEqualTo(Integer value) {
            addCriterion("static_hour <>", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourGreaterThan(Integer value) {
            addCriterion("static_hour >", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("static_hour >=", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourLessThan(Integer value) {
            addCriterion("static_hour <", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourLessThanOrEqualTo(Integer value) {
            addCriterion("static_hour <=", value, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourIn(List<Integer> values) {
            addCriterion("static_hour in", values, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourNotIn(List<Integer> values) {
            addCriterion("static_hour not in", values, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourBetween(Integer value1, Integer value2) {
            addCriterion("static_hour between", value1, value2, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStaticHourNotBetween(Integer value1, Integer value2) {
            addCriterion("static_hour not between", value1, value2, "staticHour");
            return (Criteria) this;
        }

        public Criteria andStatisYearIsNull() {
            addCriterion("statis_year is null");
            return (Criteria) this;
        }

        public Criteria andStatisYearIsNotNull() {
            addCriterion("statis_year is not null");
            return (Criteria) this;
        }

        public Criteria andStatisYearEqualTo(Integer value) {
            addCriterion("statis_year =", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearNotEqualTo(Integer value) {
            addCriterion("statis_year <>", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearGreaterThan(Integer value) {
            addCriterion("statis_year >", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("statis_year >=", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearLessThan(Integer value) {
            addCriterion("statis_year <", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearLessThanOrEqualTo(Integer value) {
            addCriterion("statis_year <=", value, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearIn(List<Integer> values) {
            addCriterion("statis_year in", values, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearNotIn(List<Integer> values) {
            addCriterion("statis_year not in", values, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearBetween(Integer value1, Integer value2) {
            addCriterion("statis_year between", value1, value2, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStatisYearNotBetween(Integer value1, Integer value2) {
            addCriterion("statis_year not between", value1, value2, "statisYear");
            return (Criteria) this;
        }

        public Criteria andStaticDayIsNull() {
            addCriterion("static_day is null");
            return (Criteria) this;
        }

        public Criteria andStaticDayIsNotNull() {
            addCriterion("static_day is not null");
            return (Criteria) this;
        }

        public Criteria andStaticDayEqualTo(Integer value) {
            addCriterion("static_day =", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayNotEqualTo(Integer value) {
            addCriterion("static_day <>", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayGreaterThan(Integer value) {
            addCriterion("static_day >", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("static_day >=", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayLessThan(Integer value) {
            addCriterion("static_day <", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayLessThanOrEqualTo(Integer value) {
            addCriterion("static_day <=", value, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayIn(List<Integer> values) {
            addCriterion("static_day in", values, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayNotIn(List<Integer> values) {
            addCriterion("static_day not in", values, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayBetween(Integer value1, Integer value2) {
            addCriterion("static_day between", value1, value2, "staticDay");
            return (Criteria) this;
        }

        public Criteria andStaticDayNotBetween(Integer value1, Integer value2) {
            addCriterion("static_day not between", value1, value2, "staticDay");
            return (Criteria) this;
        }

        public Criteria andReportDateIsNull() {
            addCriterion("report_date is null");
            return (Criteria) this;
        }

        public Criteria andReportDateIsNotNull() {
            addCriterion("report_date is not null");
            return (Criteria) this;
        }

        public Criteria andReportDateEqualTo(Integer value) {
            addCriterion("report_date =", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateNotEqualTo(Integer value) {
            addCriterion("report_date <>", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateGreaterThan(Integer value) {
            addCriterion("report_date >", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("report_date >=", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateLessThan(Integer value) {
            addCriterion("report_date <", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateLessThanOrEqualTo(Integer value) {
            addCriterion("report_date <=", value, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateIn(List<Integer> values) {
            addCriterion("report_date in", values, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateNotIn(List<Integer> values) {
            addCriterion("report_date not in", values, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateBetween(Integer value1, Integer value2) {
            addCriterion("report_date between", value1, value2, "reportDate");
            return (Criteria) this;
        }

        public Criteria andReportDateNotBetween(Integer value1, Integer value2) {
            addCriterion("report_date not between", value1, value2, "reportDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yp_merchant_statistics
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}