package com.msl.mybatis.entity;

import java.io.Serializable;

public class YpMobilePrefix implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_mobile_prefix.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_mobile_prefix.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_mobile_prefix.mobile_prefix
     *
     * @mbggenerated
     */
    private String mobilePrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_mobile_prefix.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_mobile_prefix
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_mobile_prefix.pid
     *
     * @return the value of yp_mobile_prefix.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_mobile_prefix.pid
     *
     * @param pid the value for yp_mobile_prefix.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_mobile_prefix.country
     *
     * @return the value of yp_mobile_prefix.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_mobile_prefix.country
     *
     * @param country the value for yp_mobile_prefix.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_mobile_prefix.mobile_prefix
     *
     * @return the value of yp_mobile_prefix.mobile_prefix
     *
     * @mbggenerated
     */
    public String getMobilePrefix() {
        return mobilePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_mobile_prefix.mobile_prefix
     *
     * @param mobilePrefix the value for yp_mobile_prefix.mobile_prefix
     *
     * @mbggenerated
     */
    public void setMobilePrefix(String mobilePrefix) {
        this.mobilePrefix = mobilePrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_mobile_prefix.area
     *
     * @return the value of yp_mobile_prefix.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_mobile_prefix.area
     *
     * @param area the value for yp_mobile_prefix.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }
}