package com.msl.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class YpServiceofficeDiscuss implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.merchant_user_id
     *
     * @mbggenerated
     */
    private Long merchantUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.officer_user_id
     *
     * @mbggenerated
     */
    private Long officerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_serviceoffice_discuss.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_serviceoffice_discuss
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.uuid
     *
     * @return the value of yp_serviceoffice_discuss.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.uuid
     *
     * @param uuid the value for yp_serviceoffice_discuss.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.merchant_user_id
     *
     * @return the value of yp_serviceoffice_discuss.merchant_user_id
     *
     * @mbggenerated
     */
    public Long getMerchantUserId() {
        return merchantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.merchant_user_id
     *
     * @param merchantUserId the value for yp_serviceoffice_discuss.merchant_user_id
     *
     * @mbggenerated
     */
    public void setMerchantUserId(Long merchantUserId) {
        this.merchantUserId = merchantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.officer_user_id
     *
     * @return the value of yp_serviceoffice_discuss.officer_user_id
     *
     * @mbggenerated
     */
    public Long getOfficerUserId() {
        return officerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.officer_user_id
     *
     * @param officerUserId the value for yp_serviceoffice_discuss.officer_user_id
     *
     * @mbggenerated
     */
    public void setOfficerUserId(Long officerUserId) {
        this.officerUserId = officerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.mark
     *
     * @return the value of yp_serviceoffice_discuss.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.mark
     *
     * @param mark the value for yp_serviceoffice_discuss.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.type
     *
     * @return the value of yp_serviceoffice_discuss.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.type
     *
     * @param type the value for yp_serviceoffice_discuss.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_serviceoffice_discuss.create_time
     *
     * @return the value of yp_serviceoffice_discuss.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_serviceoffice_discuss.create_time
     *
     * @param createTime the value for yp_serviceoffice_discuss.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}