package com.msl.mybatis.entity;

import java.io.Serializable;
import java.util.Date;

public class YpUserSecret implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.ref_user_id
     *
     * @mbggenerated
     */
    private Long refUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.secret_key
     *
     * @mbggenerated
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.secret_value
     *
     * @mbggenerated
     */
    private String secretValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yp_user_secret.secret_no
     *
     * @mbggenerated
     */
    private Integer secretNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yp_user_secret
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.ref_user_id
     *
     * @return the value of yp_user_secret.ref_user_id
     *
     * @mbggenerated
     */
    public Long getRefUserId() {
        return refUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.ref_user_id
     *
     * @param refUserId the value for yp_user_secret.ref_user_id
     *
     * @mbggenerated
     */
    public void setRefUserId(Long refUserId) {
        this.refUserId = refUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.secret_key
     *
     * @return the value of yp_user_secret.secret_key
     *
     * @mbggenerated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.secret_key
     *
     * @param secretKey the value for yp_user_secret.secret_key
     *
     * @mbggenerated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.secret_value
     *
     * @return the value of yp_user_secret.secret_value
     *
     * @mbggenerated
     */
    public String getSecretValue() {
        return secretValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.secret_value
     *
     * @param secretValue the value for yp_user_secret.secret_value
     *
     * @mbggenerated
     */
    public void setSecretValue(String secretValue) {
        this.secretValue = secretValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.create_time
     *
     * @return the value of yp_user_secret.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.create_time
     *
     * @param createTime the value for yp_user_secret.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.update_time
     *
     * @return the value of yp_user_secret.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.update_time
     *
     * @param updateTime the value for yp_user_secret.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yp_user_secret.secret_no
     *
     * @return the value of yp_user_secret.secret_no
     *
     * @mbggenerated
     */
    public Integer getSecretNo() {
        return secretNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yp_user_secret.secret_no
     *
     * @param secretNo the value for yp_user_secret.secret_no
     *
     * @mbggenerated
     */
    public void setSecretNo(Integer secretNo) {
        this.secretNo = secretNo;
    }
}