package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpMerchantCompanyIdentity;
import com.msl.mybatis.entity.YpMerchantCompanyIdentityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpMerchantCompanyIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int countByExample(YpMerchantCompanyIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int deleteByExample(YpMerchantCompanyIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long refUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int insert(YpMerchantCompanyIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int insertSelective(YpMerchantCompanyIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    List<YpMerchantCompanyIdentity> selectByExample(YpMerchantCompanyIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    YpMerchantCompanyIdentity selectByPrimaryKey(Long refUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpMerchantCompanyIdentity record, @Param("example") YpMerchantCompanyIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpMerchantCompanyIdentity record, @Param("example") YpMerchantCompanyIdentityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpMerchantCompanyIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_company_identity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpMerchantCompanyIdentity record);
}