package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpMerchantStatisticsVisit;
import com.msl.mybatis.entity.YpMerchantStatisticsVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpMerchantStatisticsVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int countByExample(YpMerchantStatisticsVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int deleteByExample(YpMerchantStatisticsVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer statisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int insert(YpMerchantStatisticsVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int insertSelective(YpMerchantStatisticsVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    List<YpMerchantStatisticsVisit> selectByExample(YpMerchantStatisticsVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    YpMerchantStatisticsVisit selectByPrimaryKey(Integer statisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpMerchantStatisticsVisit record, @Param("example") YpMerchantStatisticsVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpMerchantStatisticsVisit record, @Param("example") YpMerchantStatisticsVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpMerchantStatisticsVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_merchant_statistics_visit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpMerchantStatisticsVisit record);
}