package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpSysAdvert;
import com.msl.mybatis.entity.YpSysAdvertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpSysAdvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int countByExample(YpSysAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int deleteByExample(YpSysAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int insert(YpSysAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int insertSelective(YpSysAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    List<YpSysAdvert> selectByExample(YpSysAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    YpSysAdvert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpSysAdvert record, @Param("example") YpSysAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpSysAdvert record, @Param("example") YpSysAdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpSysAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_advert
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpSysAdvert record);
}