package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpSysUrlResource;
import com.msl.mybatis.entity.YpSysUrlResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpSysUrlResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int countByExample(YpSysUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int deleteByExample(YpSysUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer urlResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int insert(YpSysUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int insertSelective(YpSysUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    List<YpSysUrlResource> selectByExample(YpSysUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    YpSysUrlResource selectByPrimaryKey(Integer urlResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpSysUrlResource record, @Param("example") YpSysUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpSysUrlResource record, @Param("example") YpSysUrlResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpSysUrlResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_sys_url_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpSysUrlResource record);
}