package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpUserBank;
import com.msl.mybatis.entity.YpUserBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpUserBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int countByExample(YpUserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int deleteByExample(YpUserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int insert(YpUserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int insertSelective(YpUserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    List<YpUserBank> selectByExample(YpUserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    YpUserBank selectByPrimaryKey(Long bankId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpUserBank record, @Param("example") YpUserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpUserBank record, @Param("example") YpUserBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpUserBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpUserBank record);
}