package com.msl.mybatis.mapper;

import com.msl.mybatis.entity.YpUserBluescoreDetail;
import com.msl.mybatis.entity.YpUserBluescoreDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpUserBluescoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int countByExample(YpUserBluescoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int deleteByExample(YpUserBluescoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long blueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int insert(YpUserBluescoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int insertSelective(YpUserBluescoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    List<YpUserBluescoreDetail> selectByExample(YpUserBluescoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    YpUserBluescoreDetail selectByPrimaryKey(Long blueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpUserBluescoreDetail record, @Param("example") YpUserBluescoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpUserBluescoreDetail record, @Param("example") YpUserBluescoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YpUserBluescoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yp_user_bluescore_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YpUserBluescoreDetail record);
}